blueprint:
  name: Flexible, automatische Bereinigung verwaister Entitäten
  description: "Automatisierte Bereinigung verwaister Entitäten mit konfigurierbarer Karenzzeit und Benachrichtigungen."
  domain: automation
  source_url: https://gist.github.com/your-username/your-gist-id
  input:
    weekdays:
      name: Wochentage
      description: Die Wochentage, an denen die Automatisierung ausgeführt werden soll.
      default: ["sat"]
      selector:
        select:
          multiple: true
          options:
            - label: Montag
              value: mon
            - label: Dienstag
              value: tue
            - label: Mittwoch
              value: wed
            - label: Donnerstag
              value: thu
            - label: Freitag
              value: fri
            - label: Samstag
              value: sat
            - label: Sonntag
              value: sun
    time_of_day:
      name: Startzeit
      description: Die Uhrzeit, zu der die Automatisierung ausgeführt werden soll (HH:MM:SS).
      default: "03:00:00"
      selector:
        time:
    grace_period_weeks:
      name: Karenzzeit (in Wochen)
      description: Die Anzahl der Wochen, die eine Entität verwaist bleiben muss, bevor sie gelöscht wird.
      default: 2
      selector:
        number:
          min: 1
          max: 4
          mode: box
          unit_of_measurement: Wochen
    grace_period_hours:
      name: Zusätzliche Karenzzeit (in Stunden)
      description: Die Dauer, die eine Entität inaktiv sein muss, bevor sie gelöscht wird.
      default: 78
      selector:
        number:
          min: 1
          max: 168
          mode: box
          unit_of_measurement: Stunden
    notification_service:
      name: Benachrichtigungsdienst
      description: Der Dienst, der die Benachrichtigungen senden soll (z.B. notify.mobile_app_your_device).
      selector:
        action: {}

trigger:
  - platform: time
    at: !input time_of_day
    weekday: !input weekdays
condition: []
action:
  # 1. Schritt: Alle verwaisten Entitäten abrufen
  - alias: "Aktuelle verwaiste Entitäten abrufen"
    service: homeassistant.list_orphaned_database_entities
    response_variable: current_orphaned

  # 2. Schritt: Liste der Entitäten filtern, die länger als die Karenzzeit inaktiv waren
  - alias: "Liste der länger inaktiven Entitäten erstellen"
    variables:
      inactive_orphaned: |
        {% set result = namespace(list=[]) %}
        {% for entity_id in current_orphaned.entities %}
          {% if states(entity_id) == 'unavailable' and as_timestamp(now()) - as_timestamp(states[entity_id].last_changed) > (!input grace_period_hours | int) * 3600 %}
            {% set result.list = result.list + [entity_id] %}
          {% endif %}
        {% endfor %}
        {{ result.list }}

  # 3. Schritt: Entitäten finden, die gelöscht werden sollen (Schnittmenge der Listen)
  - variables:
      history_helper: 'input_text.homeassistant_cleanup_history'
      last_week_orphaned: "{{ states(history_helper).split(',') if states(history_helper) | length > 0 else [] }}"
      entities_to_delete: "{{ inactive_orphaned | select('in', last_week_orphaned) | list }}"

  # 4. Schritt: Lösch- und Benachrichtigungslogik ausführen
  - alias: "Löschen und Benachrichtigen"
    if: "{{ entities_to_delete | count > 0 }}"
    then:
      - alias: "Benachrichtigung mit Liste senden"
        service: !input notification_service
        data:
          title: "Home Assistant Cleanup"
          message: |
            Die folgenden {{ entities_to_delete | count }} Entitäten, die alle Kriterien erfüllen, werden gelöscht:
            {{ entities_to_delete | join('\n') }}

      - alias: "Verwaiste Entitäten löschen"
        service: recorder.purge_entities
        data:
          keep_days: 0
          entity_id: "{{ entities_to_delete }}"

      - alias: "Abschlussbenachrichtigung senden"
        service: !input notification_service
        data:
          title: "Home Assistant Cleanup abgeschlossen"
          message: "Es wurden {{ entities_to_delete | count }} Entitäten gelöscht."

    else:
      - alias: "Keine Entitäten zu löschen"
        service: !input notification_service
        data:
          title: "Home Assistant Cleanup"
          message: "Keine Entitäten gefunden, die die Kriterien für eine Löschung erfüllen."

  # 5. Schritt: Speichere die aktuelle Liste für die nächste Prüfung
  - service: input_text.set_value
    data:
      value: "{{ current_orphaned.entities | join(',') }}"
    target:
      entity_id: 'input_text.homeassistant_cleanup_history'
